"""Generate coveragepy test code from monitoring recordings."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from .probe import MonitoringRecording


def _arcs_to_arcz(arcs: set[tuple[int, int]]) -> str:
    """Convert a set of (from_line, to_line) arcs to arcz notation.

    Arcz notation uses single characters for line numbers:
      -1 is represented as '.'  (module entry/exit)
      1-9 are themselves
      10-36 are A-Z
      Negative numbers use minus prefix
    """

    def _num_to_char(n: int) -> str:
        if n == -1:
            return "."
        if n < 0:
            return f"-{_num_to_char(-n)}"
        if 0 <= n <= 9:
            return str(n)
        if 10 <= n <= 35:
            return chr(ord("A") + n - 10)
        # For numbers > 35, fall back to multi-char representation
        return str(n)

    parts = []
    for from_line, to_line in sorted(arcs):
        parts.append(f"{_num_to_char(from_line)}{_num_to_char(to_line)}")
    return " ".join(parts)


def generate_check_coverage_tests(
    recordings_dir: Path,
    class_name: str = "SysMonitorProbeTest",
) -> str:
    """Generate a test file with check_coverage() tests from recordings.

    The generated tests use coveragepy's existing test infrastructure
    and have no dependency on the monitoring probe at runtime.
    """
    recording_files = sorted(recordings_dir.glob("*.json"))
    if not recording_files:
        return ""

    # Read version from first recording
    first = json.loads(recording_files[0].read_text())
    version = ".".join(str(v) for v in first["python_version"][:3])

    lines = [
        '# Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0',
        '# For details: https://github.com/coveragepy/coveragepy/blob/main/NOTICE.txt',
        '',
        f'# Auto-generated by monitoring-probe from CPython {version}',
        f'# {len(recording_files)} snippets recorded',
        '#',
        '# To regenerate:',
        f'#   python -m monitoring_probe record snippets/ -o recordings/',
        f'#   python -m monitoring_probe generate recordings/{recordings_dir.name}/',
        '',
        'from __future__ import annotations',
        '',
        'from tests.coveragetest import CoverageTest',
        '',
        '',
        f'class {class_name}(CoverageTest):',
        f'    """Tests generated from sys.monitoring probe recordings."""',
        '',
    ]

    for rec_file in recording_files:
        data = json.loads(rec_file.read_text())
        rec = MonitoringRecording.from_dict(data)
        snippet_name = rec_file.stem

        # Format source with proper indentation for the test
        source_lines = rec.source_code.rstrip("\n").split("\n")
        indented_source = "\n".join(
            f"            {line}" if line.strip() else ""
            for line in source_lines
        )

        # Line coverage test
        sorted_lines = sorted(rec.lines_executed)
        all_source_lines = list(range(1, len(source_lines) + 1))
        # Find executable lines (lines that could potentially execute)
        missing_lines = sorted(set(all_source_lines) - rec.lines_executed)
        # Filter to likely-executable missing lines (skip blank/else/comment lines)
        executable_missing = []
        for ln in missing_lines:
            if ln <= len(source_lines):
                text = source_lines[ln - 1].strip()
                if text and not text.startswith("#") and text not in ("else:", ""):
                    executable_missing.append(ln)

        missing_str = ", ".join(str(ln) for ln in executable_missing)

        lines.append(f"    def test_{snippet_name}_lines(self) -> None:")
        lines.append(f'        self.check_coverage("""\\ ')
        lines.append(indented_source)
        lines.append(f'            """,')
        lines.append(f"            lines={sorted_lines},")
        if missing_str:
            lines.append(f'            missing="{missing_str}",')
        lines.append(f"        )")
        lines.append("")

        # Arc/branch coverage test
        arcz = _arcs_to_arcz(rec.arcs_executed)
        # Compute which arcs are "missing" — arcs that didn't happen
        # For generated tests we only know what DID execute, so branchz_missing
        # would need the full set of possible arcs from the parser.
        # Just emit branchz for now.
        lines.append(f"    def test_{snippet_name}_arcs(self) -> None:")
        lines.append(f'        self.check_coverage("""\\ ')
        lines.append(indented_source)
        lines.append(f'            """,')
        lines.append(f'            branchz="{arcz}",')
        lines.append(f"        )")
        lines.append("")

    return "\n".join(lines)


def generate_replay_json(
    recordings_dir: Path,
    output_dir: Path,
) -> int:
    """Copy recordings into the replay test data format.

    Recordings are already in the right format — this just validates
    and copies them to the target directory.
    """
    recording_files = sorted(recordings_dir.glob("*.json"))
    output_dir.mkdir(parents=True, exist_ok=True)
    count = 0
    for rec_file in recording_files:
        data = json.loads(rec_file.read_text())
        # Validate it can be deserialized
        MonitoringRecording.from_dict(data)
        out_path = output_dir / rec_file.name
        out_path.write_text(json.dumps(data, indent=2) + "\n")
        count += 1
    return count


def cmd_generate(args) -> None:  # noqa: ANN001
    """Generate test code from recordings."""
    import argparse

    recordings_dir = Path(args.recordings_dir)
    fmt = args.format

    if fmt == "check_coverage":
        output = generate_check_coverage_tests(recordings_dir)
        if args.output:
            Path(args.output).write_text(output)
            print(f"Generated tests written to {args.output}")
        else:
            print(output)
    elif fmt == "replay_json":
        if not args.output:
            print("--output required for replay_json format", file=sys.stderr)
            sys.exit(1)
        count = generate_replay_json(recordings_dir, Path(args.output))
        print(f"Copied {count} recordings to {args.output}")


def add_generate_parser(subparsers) -> None:  # noqa: ANN001
    """Add the 'generate' subcommand to the CLI parser."""
    p = subparsers.add_parser(
        "generate", help="Generate test code from recordings"
    )
    p.add_argument(
        "recordings_dir", help="Directory containing recording JSON files"
    )
    p.add_argument(
        "--format",
        choices=["check_coverage", "replay_json"],
        default="check_coverage",
        help="Output format (default: check_coverage)",
    )
    p.add_argument(
        "-o", "--output", help="Output file or directory"
    )
    p.set_defaults(func=cmd_generate)
